#!/usr/bin/env python3
"""
post_investment_reel.py — Post the "$1,000 invested in X" reel generated by
scripts/generate_investment_reel.py.

Instagram only — the Reel is the whole point of this format, and a static
chart image on Threads/Facebook would lose it.

Caption: an LLM-written 1-3 sentence hook (Anthropic API) over a fixed,
code-rendered footer carrying the exact numbers and the disclaimer — same
split as post_sector_heatmap.py/post_movers.py, so the model never restates
figures itself. Falls back to a static hook on any LLM failure.

Dedupes by date and appends the ticker to data/posted_investment_reel.json's
"tickers" history, which the generator uses to rotate through candidates.
"""

import argparse
import json
import os
import sys
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).parent))
from social_post import post_to_instagram_reel
import generate_investment_reel as reel

ROOT        = Path(__file__).parent.parent
MANIFEST    = reel.REEL_MANIFEST
TRACKING    = reel.TRACKING
MAX_HISTORY = 500
REPO        = os.environ.get("GITHUB_REPOSITORY", "sahidkhan89/sahidkhan89.github.io")
BRANCH      = os.environ.get("GITHUB_REF_NAME", "main")

HASHTAG_LINE = "#Investing"
HOOK_MAX_CHARS = 280   # the first line or two is all that shows under a Reel before "more"


def video_url(date_str: str) -> str:
    return (
        f"https://raw.githubusercontent.com/{REPO}/{BRANCH}"
        f"/images/investment-reel/{date_str}.mp4"
    )


def facts_footer(entry: dict) -> str:
    start = reel.datetime.strptime(entry["start_date"], "%Y-%m-%d").strftime("%b %Y")
    return "\n".join([
        f"${entry['ticker']}: $1,000 in {start} → {reel.fmt_money(entry['final_value'])} "
        f"({entry['pct_change']:+,.0f}%, {entry['cagr_pct']:+.1f}% a year)",
        f"S&P 500 over the same period: {reel.fmt_money(entry['bench_final'])}",
        "",
        "Which stock should we run next? Drop a ticker in the comments 👇",
        "",
        "Dividends reinvested. Past performance doesn't guarantee future returns. Not financial advice.",
        "",
        HASHTAG_LINE,
    ])


def static_hook(entry: dict) -> str:
    verb = "turned into" if entry["final_value"] >= 1000 else "shrank to"
    return (f"$1,000 in {entry['name']} {entry['years']} years ago {verb} "
            f"{reel.fmt_money(entry['final_value'])} today.")


def llm_hook(entry: dict, max_chars: int) -> str | None:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return None

    beat = entry["final_value"] > entry["bench_final"]
    facts = (
        f"Company: {entry['name']} (${entry['ticker']})\n"
        f"Period: {entry['years']} years ({entry['start_date']} to {entry['end_date']})\n"
        f"$1,000 became: {reel.fmt_money(entry['final_value'])}\n"
        f"Total return: {entry['pct_change']:+,.1f}%  (annualised {entry['cagr_pct']:+.1f}%)\n"
        f"Same $1,000 in the S&P 500: {reel.fmt_money(entry['bench_final'])}\n"
        f"Beat the S&P 500: {'yes' if beat else 'no'}"
    )
    try:
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-haiku-4-5",
                "max_tokens": 200,
                "system": (
                    "You post on Instagram for Stock Score, a stock market app for "
                    "everyday retail investors. Write the opening hook (1-3 short sentences) "
                    "for a reel showing what $1,000 invested in a stock years ago is worth "
                    "now. Make it land the surprise or the lesson: a huge winner, a stock "
                    "that lagged the S&P 500, or a long flat stretch before a breakout. "
                    "Conversational, like texting a friend, contractions fine. Factual only, "
                    "use only the numbers given, never invent events or reasons for the moves. "
                    "No investment advice, no 'you should buy'. No hashtags, no emoji, no "
                    f"quotation marks around the output. Under {max_chars} characters. "
                    "Output ONLY the hook text."
                ),
                "messages": [{"role": "user", "content": facts}],
            },
            timeout=20,
        )
        resp.raise_for_status()
        data = resp.json()
        text = next(b["text"] for b in data["content"] if b["type"] == "text").strip()
        return text[:max_chars] or None
    except Exception as e:
        print(f"  ✗ LLM hook failed, falling back to static hook: {e}")
        return None


def build_caption(entry: dict, hook: str, max_chars: int) -> str:
    footer = facts_footer(entry)
    budget = max_chars - len(footer) - 2
    if len(hook) > budget:
        hook = hook[:budget - 1] + "…"
    return f"{hook}\n\n{footer}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="Print captions and URLs without posting")
    args = parser.parse_args()

    if not MANIFEST.exists():
        print("No manifest found — nothing to post.")
        return
    entry = json.loads(MANIFEST.read_text())

    tracking = json.loads(TRACKING.read_text()) if TRACKING.exists() else {}
    posted   = tracking.get("posted", [])
    tickers  = tracking.get("tickers", [])

    if entry["date"] in posted and not args.dry_run:
        print(f"Already posted for {entry['date']} — nothing new.")
        return

    vid_url = video_url(entry["date"])
    hook = llm_hook(entry, HOOK_MAX_CHARS) or static_hook(entry)
    caption = build_caption(entry, hook, 2200)

    if args.dry_run:
        print(f"DRY RUN — {entry['date']} ({entry['ticker']})")
        print(f"  Video: {vid_url}")
        print(f"\n  ── Instagram caption ──\n{caption}")
        return

    if not (os.environ.get("IG_ACCESS_TOKEN") and os.environ.get("IG_USER_ID")):
        print("No Instagram credentials — nothing to post.")
        return

    print(f"Posting $1,000-in-{entry['ticker']} reel for {entry['date']}")
    success = False
    try:
        # Middle of the hook card's hold, so the grid cover is the question.
        thumb_offset_ms = round(
            (reel.HOOK_FADE_FRAMES + reel.HOOK_HOLD_FRAMES / 2) / reel.FPS * 1000)
        igid = post_to_instagram_reel(caption, vid_url, thumb_offset_ms=thumb_offset_ms)
        print(f"  ✓ Instagram (reel): {igid}")
        success = True
    except Exception as e:
        print(f"  ✗ Instagram: {e}")

    if success:
        tracking["posted"]  = (posted + [entry["date"]])[-MAX_HISTORY:]
        tracking["tickers"] = (tickers + [entry["ticker"]])[-MAX_HISTORY:]
        TRACKING.write_text(json.dumps(tracking, indent=2) + "\n")
        print("\nTracking file updated.")

    print("\nDone.")


if __name__ == "__main__":
    main()
