#!/usr/bin/env python3
"""
post_race_reel.py — Post the "$1,000 race" reel generated by
scripts/generate_race_reel.py. Instagram (as a Reel) and Threads (as a video
post); TikTok gets it as a draft via tiktok_post.py in the same workflow.

Caption: an LLM-written hook (Anthropic API) over a fixed footer, spoiler-free
like the other reels — the model is only given the group and member names,
never the results, so it can't leak the winner. Static hook on any LLM
failure. Dedupes by date and appends the race key to
data/posted_race_reel.json's "races" history, which the generator rotates
against.
"""

import argparse
import json
import os
import sys
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).parent))
from social_post import post_to_instagram_reel, post_to_threads_video
import generate_race_reel as reel

MANIFEST    = reel.REEL_MANIFEST
TRACKING    = reel.TRACKING
MAX_HISTORY = 500
REPO        = os.environ.get("GITHUB_REPOSITORY", "sahidkhan89/sahidkhan89.github.io")
BRANCH      = os.environ.get("GITHUB_REF_NAME", "main")

HASHTAGS = "#Stocks #Investing #StockMarket"   # max 3; tickers would be 5-7 tags
HOOK_MAX_CHARS = 280


def video_url(date_str: str) -> str:
    return (f"https://raw.githubusercontent.com/{REPO}/{BRANCH}"
            f"/images/race-reel/{date_str}.mp4")


def members(entry: dict) -> list:
    return [m["name"] for m in entry["members"] if m["ticker"] != reel.BENCH[0]]


def static_hook(entry: dict) -> str:
    return (f"$1,000 in each of {entry['title']}, {entry['years']} years ago. "
            f"Who do you think finishes first? Watch to the end.")


def llm_hook(entry: dict) -> str | None:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return None
    # Deliberately no results — the model can't spoil what it isn't told.
    facts = (f"Group: {entry['title']}\nStocks racing: {', '.join(members(entry))}, plus the S&P 500\n"
             f"Period: {entry['years']} years")
    try:
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={"x-api-key": api_key, "anthropic-version": "2023-06-01",
                     "content-type": "application/json"},
            json={
                "model": "claude-haiku-4-5",
                "max_tokens": 200,
                "system": (
                    "You post on Instagram for Stock Score, a stock market app for everyday "
                    "retail investors. Write the opening hook (1-3 short sentences) for a bar "
                    "chart race reel: $1,000 invested in each stock of a group years ago, "
                    "racing to today. Build suspense: you don't know the result, so never "
                    "state or guess the winner, any values or which stocks did well. Invite "
                    "viewers to pick a winner before the end. Conversational, contractions "
                    "fine. Never invent facts, events or numbers. No investment advice. No "
                    f"hashtags, no emoji, no quotation marks. Under {HOOK_MAX_CHARS} characters. "
                    "Output ONLY the hook text."
                ),
                "messages": [{"role": "user", "content": facts}],
            },
            timeout=20,
        )
        resp.raise_for_status()
        text = next(b["text"] for b in resp.json()["content"] if b["type"] == "text").strip()
        return text[:HOOK_MAX_CHARS] or None
    except Exception as e:
        print(f"  ✗ LLM hook failed, falling back to static hook: {e}")
        return None


def build_caption(entry: dict, hook: str, max_chars: int = 2200) -> str:
    footer = "\n".join([
        "Which group should we race next? Drop it in the comments 👇",
        "",
        "Dividends reinvested. Past performance doesn't guarantee future returns. Not financial advice.",
        "",
        HASHTAGS,
    ])
    budget = max_chars - len(footer) - 2
    if len(hook) > budget:
        hook = hook[:budget - 1] + "…"
    return f"{hook}\n\n{footer}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Print caption and URL without posting")
    args = parser.parse_args()

    if not MANIFEST.exists():
        print("No manifest found — nothing to post.")
        return
    entry = json.loads(MANIFEST.read_text())

    tracking = json.loads(TRACKING.read_text()) if TRACKING.exists() else {}
    posted, races = tracking.get("posted", []), tracking.get("races", [])
    if entry["date"] in posted and not args.dry_run:
        print(f"Already posted for {entry['date']} — nothing new.")
        return

    vid_url = video_url(entry["date"])
    hook = llm_hook(entry) or static_hook(entry)
    caption, threads_caption = build_caption(entry, hook), build_caption(entry, hook, 500)
    if args.dry_run:
        print(f"DRY RUN — {entry['date']} ({entry['race']})\n  Video: {vid_url}")
        print(f"\n  ── Threads caption (max 500) ──\n{threads_caption}")
        print(f"\n  ── Instagram caption ──\n{caption}")
        return

    has_ig      = bool(os.environ.get("IG_ACCESS_TOKEN") and os.environ.get("IG_USER_ID"))
    has_threads = bool(os.environ.get("THREADS_ACCESS_TOKEN") and os.environ.get("THREADS_USER_ID"))
    if not (has_ig or has_threads):
        print("No Instagram or Threads credentials — nothing to post.")
        return

    print(f"Posting '{entry['race']}' race reel for {entry['date']}")
    success = False
    if has_ig:
        try:
            thumb_offset_ms = round((reel.HOOK_FADE_FRAMES + reel.HOOK_HOLD_FRAMES / 2) / reel.FPS * 1000)
            igid = post_to_instagram_reel(caption, vid_url, thumb_offset_ms=thumb_offset_ms)
            print(f"  ✓ Instagram (reel): {igid}")
            success = True
        except Exception as e:
            print(f"  ✗ Instagram: {e}")

    if has_threads:
        try:
            tid = post_to_threads_video(threads_caption, vid_url)
            print(f"  ✓ Threads (video): {tid}")
            success = True
        except Exception as e:
            print(f"  ✗ Threads: {e}")

    if not success:
        return

    tracking["posted"] = (posted + [entry["date"]])[-MAX_HISTORY:]
    tracking["races"]  = (races + [entry["race"]])[-MAX_HISTORY:]
    TRACKING.write_text(json.dumps(tracking, indent=2) + "\n")
    print("\nTracking file updated.\nDone.")


if __name__ == "__main__":
    main()
