#!/usr/bin/env python3
"""
post_investment_reel.py — Post the "$1,000 invested in X" reel generated by
scripts/generate_investment_reel.py.

Instagram only — the Reel is the whole point of this format, and a static
chart image on Threads/Facebook would lose it.

Caption: an LLM-written 1-3 sentence hook (Anthropic API) over a fixed,
code-rendered footer carrying the exact numbers and the disclaimer — same
split as post_sector_heatmap.py/post_movers.py, so the model never restates
figures itself. Falls back to a static hook on any LLM failure.

Dedupes by date and appends the ticker to data/posted_investment_reel.json's
"tickers" history, which the generator uses to rotate through candidates.
"""

import argparse
import json
import os
import sys
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).parent))
from social_post import post_to_instagram_reel
import generate_investment_reel as reel

ROOT        = Path(__file__).parent.parent
MANIFEST    = reel.REEL_MANIFEST
TRACKING    = reel.TRACKING
MAX_HISTORY = 500
REPO        = os.environ.get("GITHUB_REPOSITORY", "sahidkhan89/sahidkhan89.github.io")
BRANCH      = os.environ.get("GITHUB_REF_NAME", "main")

# Max 3 hashtags: the ticker and company reach people following that stock,
# #Investing reaches the broader audience.
def _tag(text: str) -> str:
    return "#" + "".join(ch for ch in text if ch.isalnum())


def hashtag_line(entry: dict) -> str:
    tags = list(dict.fromkeys([_tag(entry["ticker"]), _tag(entry["name"]), "#Investing"]))
    if len(tags) < 3:              # ticker == name (e.g. AMD)
        tags.append("#StockMarket")
    return " ".join(tags)


HOOK_MAX_CHARS = 280   # the first line or two is all that shows under a Reel before "more"


def video_url(date_str: str) -> str:
    return (
        f"https://raw.githubusercontent.com/{REPO}/{BRANCH}"
        f"/images/investment-reel/{date_str}.mp4"
    )


def caption_footer(entry: dict) -> str:
    # No numbers anywhere in the caption — desktop Instagram shows the whole
    # caption beside the video, and the result is the reel's payoff.
    return "\n".join([
        "Which stock should we run next? Drop a ticker in the comments 👇",
        "",
        "Dividends reinvested. Past performance doesn't guarantee future returns. Not financial advice.",
        "",
        hashtag_line(entry),
    ])


def static_hook(entry: dict) -> str:
    return (f"$1,000 in {entry['name']}, {entry['years']} years ago. "
            f"What do you think it's worth today? Watch to the end.")


def llm_hook(entry: dict, max_chars: int) -> str | None:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return None

    # Deliberately no results — the model can't spoil what it isn't told.
    facts = (
        f"Company: {entry['name']} (${entry['ticker']})\n"
        f"Period: {entry['years']} years ago (since {entry['start_date'][:4]})"
    )
    try:
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-haiku-4-5",
                "max_tokens": 200,
                "system": (
                    "You post on Instagram for Stock Score, a stock market app for "
                    "everyday retail investors. Write the opening hook (1-3 short sentences) "
                    "for a reel showing what $1,000 invested in a stock years ago is worth "
                    "now. Build curiosity without giving the answer: you don't know the "
                    "result, so never state or guess the value, return or direction. Invite "
                    "viewers to guess before the end. Conversational, like texting a friend, "
                    "contractions fine. Never invent facts, events or numbers. "
                    "No investment advice, no 'you should buy'. No hashtags, no emoji, no "
                    f"quotation marks around the output. Under {max_chars} characters. "
                    "Output ONLY the hook text."
                ),
                "messages": [{"role": "user", "content": facts}],
            },
            timeout=20,
        )
        resp.raise_for_status()
        data = resp.json()
        text = next(b["text"] for b in data["content"] if b["type"] == "text").strip()
        return text[:max_chars] or None
    except Exception as e:
        print(f"  ✗ LLM hook failed, falling back to static hook: {e}")
        return None


def build_caption(entry: dict, hook: str, max_chars: int) -> str:
    footer = caption_footer(entry)
    budget = max_chars - len(footer) - 2
    if len(hook) > budget:
        hook = hook[:budget - 1] + "…"
    return f"{hook}\n\n{footer}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="Print captions and URLs without posting")
    args = parser.parse_args()

    if not MANIFEST.exists():
        print("No manifest found — nothing to post.")
        return
    entry = json.loads(MANIFEST.read_text())

    tracking = json.loads(TRACKING.read_text()) if TRACKING.exists() else {}
    posted   = tracking.get("posted", [])
    tickers  = tracking.get("tickers", [])

    if entry["date"] in posted and not args.dry_run:
        print(f"Already posted for {entry['date']} — nothing new.")
        return

    vid_url = video_url(entry["date"])
    hook = llm_hook(entry, HOOK_MAX_CHARS) or static_hook(entry)
    caption = build_caption(entry, hook, 2200)

    if args.dry_run:
        print(f"DRY RUN — {entry['date']} ({entry['ticker']})")
        print(f"  Video: {vid_url}")
        print(f"\n  ── Instagram caption ──\n{caption}")
        return

    if not (os.environ.get("IG_ACCESS_TOKEN") and os.environ.get("IG_USER_ID")):
        print("No Instagram credentials — nothing to post.")
        return

    print(f"Posting $1,000-in-{entry['ticker']} reel for {entry['date']}")
    success = False
    try:
        # Middle of the hook card's hold, so the grid cover is the question.
        thumb_offset_ms = round(
            (reel.HOOK_FADE_FRAMES + reel.HOOK_HOLD_FRAMES / 2) / reel.FPS * 1000)
        igid = post_to_instagram_reel(caption, vid_url, thumb_offset_ms=thumb_offset_ms)
        print(f"  ✓ Instagram (reel): {igid}")
        success = True
    except Exception as e:
        print(f"  ✗ Instagram: {e}")

    if success:
        tracking["posted"]  = (posted + [entry["date"]])[-MAX_HISTORY:]
        tracking["tickers"] = (tickers + [entry["ticker"]])[-MAX_HISTORY:]
        TRACKING.write_text(json.dumps(tracking, indent=2) + "\n")
        print("\nTracking file updated.")

    print("\nDone.")


if __name__ == "__main__":
    main()
