#!/usr/bin/env python3
"""
post_h2h_reel.py — Post the "$1,000 in A vs B" head-to-head reel generated by
scripts/generate_h2h_reel.py.

Same shape as post_investment_reel.py: Instagram (as a Reel) and Threads (as
a video post), with the caption an LLM-written hook over a code-rendered facts
footer (static hook on any LLM failure). Dedupes by date and appends the pair to data/posted_h2h_reel.json's
"matchups" history, which the generator rotates against.
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).parent))
from social_post import post_to_instagram_reel, post_to_threads_video
import generate_h2h_reel as reel

MANIFEST    = reel.REEL_MANIFEST
TRACKING    = reel.TRACKING
MAX_HISTORY = 500
REPO        = os.environ.get("GITHUB_REPOSITORY", "sahidkhan89/sahidkhan89.github.io")
BRANCH      = os.environ.get("GITHUB_REF_NAME", "main")

# Max 3 hashtags: both tickers, plus #Investing for the broader audience.
def _tag(text: str) -> str:
    return "#" + "".join(ch for ch in text if ch.isalnum())


def hashtag_line(entry: dict) -> str:
    return " ".join([_tag(entry["a"]["ticker"]), _tag(entry["b"]["ticker"]), "#Investing"])


HOOK_MAX_CHARS = 280   # the first line or two is all that shows under a Reel before "more"


def video_url(date_str: str) -> str:
    return (
        f"https://raw.githubusercontent.com/{REPO}/{BRANCH}"
        f"/images/h2h-reel/{date_str}.mp4"
    )


def caption_footer(entry: dict) -> str:
    # No numbers anywhere in the caption — desktop Instagram shows the whole
    # caption beside the video, so listing the results would spoil the race.
    return "\n".join([
        "Which matchup should we run next? Drop it in the comments 👇",
        "",
        "Dividends reinvested. Past performance doesn't guarantee future returns. Not financial advice.",
        "",
        hashtag_line(entry),
    ])


def static_hook(entry: dict) -> str:
    # Never names the winner — the first caption line shows under the reel,
    # and spoiling the result there undercuts the "who wins?" hook.
    a, b = entry["a"], entry["b"]
    return (f"{a['name']} vs {b['name']}: $1,000 in each, {entry['years']} years ago. "
            f"Make your guess before the end.")


def llm_hook(entry: dict, max_chars: int) -> str | None:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return None

    a, b = entry["a"], entry["b"]
    # Deliberately no results — the model can't spoil what it isn't told.
    facts = (
        f"Matchup: {a['name']} (${a['ticker']}) vs {b['name']} (${b['ticker']})\n"
        f"Period: {entry['years']} years ago (since {entry['start_date'][:4]})"
    )
    try:
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-haiku-4-5",
                "max_tokens": 200,
                "system": (
                    "You post on Instagram for Stock Score, a stock market app for "
                    "everyday retail investors. Write the opening hook (1-3 short sentences) "
                    "for a head-to-head reel: $1,000 in one stock vs $1,000 in its rival, "
                    "years ago. Build suspense: play up the rivalry and tease the race. You "
                    "don't know the result, so never state or guess which stock won or any "
                    "values. Invite viewers to guess before the end. Conversational, "
                    "contractions fine. Never invent facts, events or numbers. "
                    "No investment advice. No hashtags, no emoji, no quotation "
                    f"marks around the output. Under {max_chars} characters. Output ONLY the hook text."
                ),
                "messages": [{"role": "user", "content": facts}],
            },
            timeout=20,
        )
        resp.raise_for_status()
        data = resp.json()
        text = next(b["text"] for b in data["content"] if b["type"] == "text").strip()
        return text[:max_chars] or None
    except Exception as e:
        print(f"  ✗ LLM hook failed, falling back to static hook: {e}")
        return None


def build_caption(entry: dict, hook: str, max_chars: int) -> str:
    footer = caption_footer(entry)
    budget = max_chars - len(footer) - 2
    if len(hook) > budget:
        hook = hook[:budget - 1] + "…"
    return f"{hook}\n\n{footer}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="Print captions and URLs without posting")
    args = parser.parse_args()

    if not MANIFEST.exists():
        print("No manifest found — nothing to post.")
        return
    entry = json.loads(MANIFEST.read_text())

    tracking = json.loads(TRACKING.read_text()) if TRACKING.exists() else {}
    posted   = tracking.get("posted", [])
    matchups = tracking.get("matchups", [])

    if entry["date"] in posted and not args.dry_run:
        print(f"Already posted for {entry['date']} — nothing new.")
        return

    vid_url = video_url(entry["date"])
    hook = llm_hook(entry, HOOK_MAX_CHARS) or static_hook(entry)
    caption = build_caption(entry, hook, 2200)
    threads_caption = build_caption(entry, hook, 500)

    if args.dry_run:
        print(f"DRY RUN — {entry['date']} ({entry['pair']})")
        print(f"  Video: {vid_url}")
        print(f"\n  ── Threads caption (max 500) ──\n{threads_caption}")
        print(f"\n  ── Instagram caption ──\n{caption}")
        return

    has_ig      = bool(os.environ.get("IG_ACCESS_TOKEN") and os.environ.get("IG_USER_ID"))
    has_threads = bool(os.environ.get("THREADS_ACCESS_TOKEN") and os.environ.get("THREADS_USER_ID"))
    if not (has_ig or has_threads):
        print("No Instagram or Threads credentials — nothing to post.")
        return

    print(f"Posting {entry['pair']} head-to-head reel for {entry['date']}")
    success = False
    if has_ig:
        try:
            # Middle of the hook card's hold, so the grid cover is the question.
            thumb_offset_ms = round(
                (reel.HOOK_FADE_FRAMES + reel.HOOK_HOLD_FRAMES / 2) / reel.FPS * 1000)
            igid = post_to_instagram_reel(caption, vid_url, thumb_offset_ms=thumb_offset_ms)
            print(f"  ✓ Instagram (reel): {igid}")
            success = True
        except Exception as e:
            print(f"  ✗ Instagram: {e}")

    if has_threads:
        try:
            tid = post_to_threads_video(threads_caption, vid_url)
            print(f"  ✓ Threads (video): {tid}")
            success = True
        except Exception as e:
            print(f"  ✗ Threads: {e}")

    if success:
        tracking["posted"]   = (posted + [entry["date"]])[-MAX_HISTORY:]
        tracking["matchups"] = (matchups + [entry["pair"]])[-MAX_HISTORY:]
        TRACKING.write_text(json.dumps(tracking, indent=2) + "\n")
        print("\nTracking file updated.")

    print("\nDone.")


if __name__ == "__main__":
    main()
