#!/usr/bin/env python3
"""
post_guess_reel.py — Post the "Guess the stock" reel generated by
scripts/generate_guess_reel.py. Instagram only (TikTok gets it as a draft via
tiktok_post.py in the same workflow).

The caption must not give the answer away, so unlike the other reels there's
no LLM hook (anything written about the company is a clue) and no ticker
hashtags — just a rotating set of fixed hooks, the comment prompt and the
disclaimer. Dedupes by date and appends the ticker to
data/posted_guess_reel.json's "tickers" history, which the generator rotates
against.
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from social_post import post_to_instagram_reel
import generate_guess_reel as reel

MANIFEST    = reel.REEL_MANIFEST
TRACKING    = reel.TRACKING
MAX_HISTORY = 500
REPO        = os.environ.get("GITHUB_REPOSITORY", "sahidkhan89/sahidkhan89.github.io")
BRANCH      = os.environ.get("GITHUB_REF_NAME", "main")

HASHTAGS = "#GuessTheStock #Stocks #Investing"   # max 3, and never the answer

HOOKS = [
    "Mystery stock, {years} years of price history. Can you name it before the reveal?",
    "$1,000 in a mystery stock, {years} years ago. Guess it before the countdown ends.",
    "Two hints, one countdown. How fast can you name this stock?",
    "Here's {years} years of a stock you've definitely heard of. Which one is it?",
]


def video_url(date_str: str) -> str:
    return (f"https://raw.githubusercontent.com/{REPO}/{BRANCH}"
            f"/images/guess-reel/{date_str}.mp4")


def build_caption(entry: dict) -> str:
    day = datetime.strptime(entry["date"], "%Y-%m-%d").toordinal()
    hook = HOOKS[day % len(HOOKS)].format(years=entry["years"])
    return "\n".join([
        hook,
        "",
        "Comment your guess before you watch the reveal 👇",
        "",
        "Dividends reinvested. Past performance doesn't guarantee future returns. Not financial advice.",
        "",
        HASHTAGS,
    ])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Print caption and URL without posting")
    args = parser.parse_args()

    if not MANIFEST.exists():
        print("No manifest found — nothing to post.")
        return
    entry = json.loads(MANIFEST.read_text())

    tracking = json.loads(TRACKING.read_text()) if TRACKING.exists() else {}
    posted, tickers = tracking.get("posted", []), tracking.get("tickers", [])
    if entry["date"] in posted and not args.dry_run:
        print(f"Already posted for {entry['date']} — nothing new.")
        return

    vid_url, caption = video_url(entry["date"]), build_caption(entry)
    if args.dry_run:
        print(f"DRY RUN — {entry['date']} ({entry['ticker']})\n  Video: {vid_url}")
        print(f"\n  ── Instagram caption ──\n{caption}")
        return

    if not (os.environ.get("IG_ACCESS_TOKEN") and os.environ.get("IG_USER_ID")):
        print("No Instagram credentials — nothing to post.")
        return

    print(f"Posting guess-the-stock reel for {entry['date']}")
    try:
        # Middle of the hook card's hold, so the grid cover is the question.
        thumb_offset_ms = round((reel.HOOK_FADE_FRAMES + reel.HOOK_HOLD_FRAMES / 2) / reel.FPS * 1000)
        igid = post_to_instagram_reel(caption, vid_url, thumb_offset_ms=thumb_offset_ms)
        print(f"  ✓ Instagram (reel): {igid}")
    except Exception as e:
        print(f"  ✗ Instagram: {e}")
        return

    tracking["posted"]  = (posted + [entry["date"]])[-MAX_HISTORY:]
    tracking["tickers"] = (tickers + [entry["ticker"]])[-MAX_HISTORY:]
    TRACKING.write_text(json.dumps(tracking, indent=2) + "\n")
    print("\nTracking file updated.\nDone.")


if __name__ == "__main__":
    main()
